services:
  - type: web
    name: moneytracker-backend
    env: node
    region: singapore
    buildCommand: yarn install && yarn build:server
    startCommand: yarn start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false