services:
  - type: web
    name: moneytracker-backend
    env: node
    region: singapore
    buildCommand: cd server && yarn install && yarn build
    startCommand: cd server && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false